name: Lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install modules
      run: npm ci
    - uses: sibiraj-s/action-eslint@v2
      with:
        eslint-args: '. --fix --ignore-path=.gitignore'
        extensions: 'js,jsx,ts,tsx'
        annotations: true
